pagopa/arc-infra

- src/06_domains/cittadini-app/04_k8s_configmaps.tf
- src/06_domains/cittadini-app/99_variables.tf
- src/06_domains/cittadini-app/README.md
- src/06_domains/cittadini-app/env/itn-dev/terraform.tfvars
- src/06_domains/cittadini-common/02_serviceaccounts_azure_devops.tf
- src/06_domains/cittadini-common/README.md
- src/06_domains/cittadini-secrets/00_data.tf
- src/06_domains/cittadini-secrets/03_azdo.tf
- src/06_domains/cittadini-secrets/99_locals.tf
> feat: Add config map

- src/05_aks/03_keda.tf
- src/05_aks/99_variables.tf
- src/05_aks/README.md
- src/05_aks/env/itn-dev/terraform.tfvars
- src/06_domains/cittadini-common/.terraform.lock.hcl
- src/06_domains/cittadini-common/01_aks.tf
- src/06_domains/cittadini-common/99_locals.tf
- src/06_domains/cittadini-common/99_main.tf
- src/06_domains/cittadini-common/99_variables.tf
- src/06_domains/cittadini-common/README.md
- src/06_domains/cittadini-common/env/itn-dev/terraform.tfvars
- src/06_domains/cittadini-common/helm/cert-mounter.yaml.tpl
> feat: Upgrade aks & helm reloader cert mounter & keda

- src/06_domains/cittadini-secrets/02_key_secret.tf
- src/06_domains/cittadini-secrets/secret/itn-dev/noedit_secret_enc.json
- src/06_domains/cittadini-secrets/secret/itn-dev/secret.ini
> feat: P4PU-263 - Add postman environment secret

- src/02_security/secret/itn-prod/noedit_secret_enc.json
> feat: add sonar token

- src/06_domains/cittadini-app/04_k8s_configmaps.tf
- src/06_domains/cittadini-app/99_variables.tf
- src/06_domains/cittadini-app/README.md
- src/06_domains/cittadini-app/env/itn-dev/terraform.tfvars
- src/06_domains/cittadini-secrets/secret/itn-dev/noedit_secret_enc.json
> feat: P4PU-285 - Payments pull subscription key

- .github/workflows/pr-title.yml
- scripts/terraform.sh
- src/06_domains/cittadini-common/.terraform.lock.hcl
- src/06_domains/cittadini-common/00_data.tf
- src/06_domains/cittadini-common/01_aks.tf
- src/06_domains/cittadini-common/02_serviceaccounts_azure_devops.tf
- src/06_domains/cittadini-common/07_cdn.tf
- src/06_domains/cittadini-common/08_security.tf
- src/06_domains/cittadini-common/99_locals.tf
- src/06_domains/cittadini-common/99_main.tf
- src/06_domains/cittadini-common/README.md
- src/06_domains/cittadini-secrets/.terraform.lock.hcl
- src/06_domains/cittadini-secrets/99_main.tf
> feat: [P4PU-331] Add jwt keys

- .github/workflows/pr-title.yml
- src/02_security/.terraform.lock.hcl
- src/02_security/99_main.tf
- src/02_security/README.md
- src/02_security/secret/itn-prod/noedit_secret_enc.json
> feat: [P4PU-357] add one trust api key

- src/06_domains/cittadini-secrets/secret/itn-dev/noedit_secret_enc.json
> feat: [P4PU-355] Store subscription key (debt position, pull payment, biz events)

- src/06_domains/cittadini-app/env/itn-dev/terraform.tfvars
> fix: [P4PU-372] update gpd payments pull

- src/06_domains/cittadini-common/07_cdn.tf
> fix: [P4PU-388] Cdn error page

- src/06_domains/cittadini-app/04_k8s_configmaps.tf
- src/06_domains/cittadini-app/README.md
- src/06_domains/cittadini-secrets/secret/itn-dev/noedit_secret_enc.json
> feat: [P4PU-367] zendesk secret

- src/04_core/.terraform.lock.hcl
- src/04_core/env/itn-prod/backend.ini
- src/04_core/env/itn-prod/backend.tfvars
- src/04_core/env/itn-prod/terraform.tfvars
Allow to have ACR in prod and link a service connection for azdo
---
> feat: Azure container registry in prod

- src/05_aks/env/itn-dev/terraform.tfvars
- src/06_domains/cittadini-secrets/secret/itn-dev/noedit_secret_enc.json
- src/06_domains/cittadini-secrets/secret/itn-uat/noedit_secret_enc.json
> feat: P4PU-418 - Upgrade cilium dev

- src/06_domains/cittadini-app/.terraform.lock.hcl
- src/06_domains/cittadini-app/04_k8s_configmaps.tf
updated value `arc-help-center-url = " https://portalearc.zendesk.com/hc/it/requests/new"`
---
> fix(cittadino): updated config map for arc-help-center-url

- src/06_domains/cittadini-secrets/secret/itn-uat/noedit_secret_enc.json
> feat: P4PU-443 Align one identity secrets

- src/06_domains/cittadini-app/.terraform.lock.hcl
- src/06_domains/cittadini-app/04_k8s_configmaps.tf
> fix(cittadini): typo fix

- src/06_domains/cittadini-app/04_k8s_configmaps.tf
> feat: Update zendesk config map

- .devops/README.md
- .devops/base-code-review-pipelines.yml
- .devops/base-deploy-pipelines.yml
- .devops/cittadini-code-review-pipelines.yml
- .devops/cittadini-deploy-pipelines.yml
- .devops/core-code-review-pipelines.yml
- .devops/core-deploy-pipelines.yml
- .devops/networking-code-review-pipelines.yml
- .devops/networking-deploy-pipelines.yml
- .devops/packer-code-review-pipelines.yml
- .devops/packer-deploy-pipelines.yml
- .devops/security-code-review-pipelines.yml
- .devops/security-deploy-pipelines.yml
- scripts/terraform.sh
- src/02_security/.terraform.lock.hcl
- src/02_security/00_azdo.tf
- src/02_security/01_core_security.tf
- src/02_security/99_locals.tf
- src/02_security/README.md
- src/04_core/08_custom_roles.tf
- src/04_core/README.md
- src/06_domains/cittadini-common/.terraform.lock.hcl
- src/06_domains/cittadini-secrets/01_security.tf
- src/06_domains/cittadini-secrets/99_locals.tf
> feat: Iac pipelines

- src/06_domains/cittadini-secrets/secret/itn-dev/noedit_secret_enc.json
> feat: P4PU-120 testing username and password

- src/06_domains/cittadini-secrets/secret/itn-dev/noedit_secret_enc.json
- src/06_domains/cittadini-secrets/secret/itn-uat/noedit_secret_enc.json
> feat: P4PU-580 secret cf @dev@uat

- scripts/sops.sh
- scripts/terrasops.sh
- src/02_security/.terraform.lock.hcl
- src/02_security/00_azdo.tf
- src/02_security/01_core_security.tf
- src/02_security/02_init_sops.tf
- src/02_security/02_key_secret.tf
- src/02_security/99_locals.tf
- src/02_security/99_main.tf
- src/02_security/README.md
> feat: P4PU-567 security@prod & new sops

- src/01_networking/.terraform.lock.hcl
- src/01_networking/99_locals.tf
- src/01_networking/99_main.tf
- src/01_networking/99_variables.tf
- src/01_networking/README.md
- src/01_networking/env/itn-dev/terraform.tfvars
- src/01_networking/env/itn-prod/terraform.tfvars
- src/01_networking/env/itn-uat/terraform.tfvars
> feat: P4PU-566 network@prod

- src/06_domains/cittadini-secrets/secret/itn-dev/secret.ini
- src/06_domains/cittadini-secrets/secret/itn-uat/secret.ini
> fix: Config sops

- src/06_domains/cittadini-secrets/01_security.tf
> fix: Cittadini access policy

- src/01_networking/02_private_network.tf
- src/01_networking/README.md
- src/06_domains/cittadini-common/00_data.tf
- src/06_domains/cittadini-common/05_redis.tf
- src/06_domains/cittadini-common/99_variables.tf
- src/06_domains/cittadini-common/README.md
- src/06_domains/cittadini-common/env/itn-dev/terraform.tfvars
- src/06_domains/cittadini-common/env/itn-uat/terraform.tfvars
> feat: P4PU-548 add redis

- src/06_domains/cittadini-secrets/secret/itn-dev/noedit_secret_enc.json
- src/06_domains/cittadini-secrets/secret/itn-uat/noedit_secret_enc.json
> feat: P4PU-633 add e2e credentials

- src/02_security/secret/itn-prod/noedit_secret_enc.json
- src/04_core/env/itn-dev/terraform.tfvars
- src/04_core/env/itn-prod/terraform.tfvars
> feat: P4PU-573 core@prod

- src/06_domains/cittadini-secrets/.terraform.lock.hcl
- src/06_domains/cittadini-secrets/secret/itn-dev/noedit_secret_enc.json
- src/06_domains/cittadini-secrets/secret/itn-uat/noedit_secret_enc.json
- src/06_domains/cittadini-secrets/win_sops.sh
- src/06_domains/cittadini-secrets/win_terraform.sh
> feat: [P4PU-650] added secret for slack

- .pre-commit-config.yaml
- src/06_domains/cittadini-app/.terraform.lock.hcl
- src/06_domains/cittadini-app/00_data.tf
- src/06_domains/cittadini-app/00_kv.tf
- src/06_domains/cittadini-app/30_argocd.tf
- src/06_domains/cittadini-app/99_main.tf
- src/06_domains/cittadini-app/99_variables.tf
- src/06_domains/cittadini-app/env/itn-dev/terraform.tfvars
- src/06_domains/cittadini-app/env/itn-uat/terraform.tfvars
- src/06_domains/cittadini-secrets/secret/itn-dev/noedit_secret_enc.json
- src/06_domains/cittadini-secrets/secret/itn-uat/noedit_secret_enc.json
- added argocd root_app and project
- added argocd secrets
Allow to use cittadini inside argocd
---
> feat: [P4PU-645] argocd setup for cittadini domain

- src/06_domains/cittadini-app/workbooks/OPEXWorkbook.json.tpl
- updated query Availability
---
> fix: [P4PU-655] updated query Availability

- src/06_domains/cittadini-secrets/secret/itn-prod/noedit_secret_enc.json
> fix: prod argocd password for cittadini

- src/06_domains/cittadini-app/.terraform.lock.hcl
- src/06_domains/cittadini-app/12_alert.tf
added allarm for ram availability
---
> feat: [P4PU-671] added allarm for ram availability

- src/06_domains/cittadini-app/k8s-file/appinsights-config/applicationinsights.json
added sampling into applicationinsights.json
---
> chore: [P4PU-691] added sampling into applicationinsights.json

- src/06_domains/cittadini-app/00_data.tf
- src/06_domains/cittadini-app/12_alert.tf
> feat: [P4PU-680] added allarm for redis

- src/06_domains/cittadini-app/.terraform.lock.hcl
- src/06_domains/cittadini-app/04_k8s_configmaps.tf
- updated arc help center url
---
> fix: [P4PU-686] updated arc help center url

- src/04_core/env/itn-prod/terraform.tfvars
- src/06_domains/cittadini-app/env/itn-prod/terraform.tfvars
> feat: P4PU-664 enabled alerts apim & cittadini domains

- src/06_domains/cittadini-secrets/secret/itn-dev/noedit_secret_enc.json
- src/06_domains/cittadini-secrets/secret/itn-uat/noedit_secret_enc.json
- added connection string secret
---
> feat: [P4PU-674] added connection string secret

- src/06_domains/cittadini-app/04_k8s_configmaps.tf
- update organization for assistance
---
> fix: [P4PU-759] update organization for assistance

- src/06_domains/cittadini-app/04_k8s_configmaps.tf
- src/06_domains/cittadini-app/99_variables.tf
- src/06_domains/cittadini-app/env/itn-dev/terraform.tfvars
- src/06_domains/cittadini-app/env/itn-prod/terraform.tfvars
- src/06_domains/cittadini-app/env/itn-uat/terraform.tfvars
- src/06_domains/cittadini-secrets/secret/itn-prod/noedit_secret_enc.json
> feat: P4PU-760 add gpd debt positions key & config map

- src/03_packer/99_main.tf
- src/03_packer/README.md
- src/03_packer/env/itn-dev/terraform.tfvars
- src/03_packer/env/itn-prod/terraform.tfvars
- src/03_packer/env/itn-uat/terraform.tfvars
- src/04_core/env/itn-dev/terraform.tfvars
- src/04_core/env/itn-prod/terraform.tfvars
- src/04_core/env/itn-uat/terraform.tfvars
- packer: update image with argocd and temporal
- vmss azdo update
Allow to use argocd into azdo agents
---
> feat: P4PU-789 azdo vmss update with new packer image

- src/04_core/05_appgateway_core.tf
- src/04_core/99_main.tf
- src/04_core/99_variables.tf
- src/04_core/README.md
- src/04_core/env/itn-dev/terraform.tfvars
- src/04_core/env/itn-prod/terraform.tfvars
- src/04_core/env/itn-uat/terraform.tfvars
> feat: P4PU-697 upgrade apim appgw

- src/04_core/02_monitor.tf
- src/05_monitoring/01_analytics_workspace.tf
> feat: Log analytics ignore sku

- src/05_aks/99_main.tf
- src/05_aks/README.md
> feat: PAYMCLOUD-228 prometheus production ready

- src/06_domains/cittadini-common/07_cdn.tf
> fix: P4PU-847 csp fix

- src/06_domains/cittadini-app/workbooks/OPEXWorkbook.json.tpl
- added external dependency gpd on workbook
---
> fix: [P4PU-873] added external dependency gpd on workbook

- src/05_aks/02_aks.tf
> feat: Disable pod identity
